# Generated by Django 5.2.8 on 2025-11-24 00:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendships', '0002_alter_friendship_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='friendship',
            new_name='friendships_from_us_6c3805_idx',
            old_fields=('from_user', 'created_at'),
        ),
        migrations.RenameIndex(
            model_name='friendship',
            new_name='friendships_to_user_3e9003_idx',
            old_fields=('to_user', 'created_at'),
        ),
        migrations.AlterUniqueTogether(
            name='friendship',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='friendship',
            constraint=models.UniqueConstraint(fields=('from_user', 'to_user'), name='unique_from_user_to_user'),
        ),
    ]
