# Generated by Django 5.2.8 on 2025-11-24 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='comment',
            new_name='comments_co_tweet_i_704e78_idx',
            old_fields=('tweet', 'created_at'),
        ),
    ]
