# Generated by Django 3.2.21 on 2026-06-10 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeeds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsfeed',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
