# Generated by Django 5.2.8 on 2025-11-24 00:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeeds', '0001_initial'),
        ('tweets', '0003_rename_tweet_user_created_at_tweets_twee_user_id_ba0f61_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='newsfeed',
            new_name='newsfeeds_n_user_id_16c5ef_idx',
            old_fields=('user', 'created_at'),
        ),
        migrations.AlterUniqueTogether(
            name='newsfeed',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='newsfeed',
            constraint=models.UniqueConstraint(fields=('user', 'tweet'), name='unique_user_tweet'),
        ),
    ]
