# Generated by Django 3.2.21 on 2026-07-06 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_auto_20251213_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='moderation_status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Safe'), (2, 'Flagged')], default=0),
        ),
    ]
