# Generated by Django 5.2.8 on 2025-11-24 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_alter_tweet_options_alter_tweet_index_together'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='tweet',
            new_name='tweets_twee_user_id_ba0f61_idx',
            old_fields=('user', 'created_at'),
        ),
    ]
