"""
Django settings for twitter project.

Generated by 'django-admin startproject' using Django 4.2.25.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import sys
from pathlib import Path

from kombu import Queue

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-8$!(l%_g+2@_zo20t60o!$a3djbwonviy)zv$zs($=y6lfw1x!'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['127.0.0.1', '192.168.33.10', 'localhost',]
INTERNAL_IPS = ['10.0.2.2',]


# Application definition
INSTALLED_APPS = [
    # django default
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # third party packages
    'rest_framework',
    "debug_toolbar",
    'django_filters',
    'notifications',
    'storages',

    # project apps
    'accounts',
    'tweets',
    'friendships',
    'newsfeeds',
    'comments',
    'likes',
    'inbox',
    'testing',
]

REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,    # PAGE_SIZE: 通常需要服务端做上限限制, 防止恶意请求拉取超大数据集
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend',],
    'EXCEPTION_HANDLER': 'utils.ratelimit.exception_handler',
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    "debug_toolbar.middleware.DebugToolbarMiddleware",
]

ROOT_URLCONF = 'twitter.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'twitter.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'twitter',
        'HOST': '127.0.0.1',
        'PORT': '3306',
        'USER': 'root',
        'PASSWORD': 'zhuzhu',
    }
}

# HBase Database
HBASE_HOST = '127.0.0.1'

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/
STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 设置默认文件存储系统: Amazon S3
# 单元测试时使用本地存储 (避免依赖 AWS)
DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
TESTING = ((" ".join(sys.argv)).find('manage.py test') != -1)
if TESTING:
    DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'

AWS_STORAGE_BUCKET_NAME = 'django-twitter-zhuzhu'
AWS_S3_REGION_NAME = 'us-west-1'
MEDIA_ROOT = 'media/'


#   use_pooling=True: 每线程独立连接, 根治 pymemcache 单 socket 多线程共享导致的 "响应错位"
#                     (线程A 收到线程B 的响应)
#   ignore_exc=True:  memcached 故障时 get 返回 None(当作 cache miss 回源 DB), set 静默失败
#                     => 缓存 best-effort, 挂了不把故障放大成整站异常 (MemcachedHelper 已是 get->miss->DB->set)
MEMCACHED_OPTIONS = {'use_pooling': True, 'ignore_exc': True}
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.memcached.PyMemcacheCache',
        'LOCATION': '127.0.0.1:11211',
        'TIMEOUT': 86400,
        'OPTIONS': MEMCACHED_OPTIONS,
    },
    'testing': {    # 测试环境缓存(避免 key 冲突)
        'BACKEND': 'django.core.cache.backends.memcached.PyMemcacheCache',
        'LOCATION': '127.0.0.1:11211',
        'TIMEOUT': 86400,
        'KEY_PREFIX': 'testing', # 实际存储 key 示例: 'testing_followings:3'
        'OPTIONS': MEMCACHED_OPTIONS,
    },
    'ratelimit': {  # 限流专用缓存
        'BACKEND': 'django.core.cache.backends.memcached.PyMemcacheCache',
        'LOCATION': '127.0.0.1:11211',
        'TIMEOUT': 86400 * 7,
        'KEY_PREFIX': 'rl',
        'OPTIONS': MEMCACHED_OPTIONS,
    },
}

RATELIMIT_USE_CACHE = 'ratelimit'
RATELIMIT_ENABLE = not TESTING  # 是否开启限流 (测试环境一般关闭)


REDIS_HOST = '127.0.0.1'
REDIS_PORT = 6379
REDIS_DB = 0 if TESTING else 1
REDIS_KEY_EXPIRE_TIME = 7 * 86400
REDIS_LIST_LENGTH_LIMIT = 200 if not TESTING else 20
# 控制 Redis 列表缓存的最大长度(newsfeed/tweet), 防止一次性从数据库读取过多数据, 降低 DB 压力和 Redis 内存占用

CELERY_BROKER_URL = 'redis://127.0.0.1:6379/2' if not TESTING else 'redis://127.0.0.1:6379/0'
# 测试与生产使用不同 Redis DB, 不要让 cache DB 和 broker DB 混用！
CELERY_TIMEZONE = 'UTC'
CELERY_TASK_ALWAYS_EAGER = TESTING      # 测试环境下任务同步执行
CELERY_TASK_EAGER_PROPAGATES = TESTING
CELERY_TASK_QUEUES = (
    Queue(name='default', routing_key='default'),
    Queue(name='newsfeeds', routing_key='newsfeeds'),
)
CELERY_TASK_ROUTES = {
    'newsfeeds.tasks.fanout_newsfeeds_main_task': {'queue': 'default'},
    'newsfeeds.tasks.fanout_newsfeeds_batch_task': {'queue': 'newsfeeds'},
}


try:
    from twitter.local_settings import *
except ImportError:
    # 仅当 local_settings.py 不存在时静默跳过;
    # 文件存在但内部有语法/拼写错误会照常抛出
    pass