"""
Django settings for twitter project.

Generated by 'django-admin startproject' using Django 4.2.25.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import sys

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-8$!(l%_g+2@_zo20t60o!$a3djbwonviy)zv$zs($=y6lfw1x!'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['127.0.0.1', '192.168.33.10', 'localhost',]
INTERNAL_IPS = ['10.0.2.2',]
"""
在 Vagrant + VirtualBox NAT 网络模式中：

- 虚拟机自己的 IP 通常为：10.0.2.15
- 虚拟机看到的宿主机 IP 是：10.0.2.2
- 端口映射把宿主机端口转发到虚拟机端口，例如：host:80 → guest:8000

所以 request.META['REMOTE_ADDR'] 为 10.0.2.2 表示：请求来自“宿主机浏览器”。
"""

# Application definition
"""
A. 当前架构现状
    1. 所有模块部署在同一台服务器
    2. 使用同一个代码库(Git repo)，同一个 runtime
    3. 模块间可以直接 from xxx import yyy
    
B. 拆分为微服务, 每个服务
    1. 运行在不同 server/container (Docker/K8s), 
    2. 独立 Git repo, 独立部署发布
    3. 通过 API（HTTP/GRPC, protobuf/Thrift）互相调用, 代码量显著增加

好处
    解耦，每个模块独立演化: accounts 在 Twitter、直播、短视频等多个产品都能重用
    可以独立扩容: tweets QPS 很高 → 单独扩容 tweets-service
    技术栈可自由选择: accounts 使用 Django; tweets 使用 Go + Redis + Cassandra
"""
INSTALLED_APPS = [
    # django default
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # third party packages
    'rest_framework',
    "debug_toolbar",
    'django_filters',
    'notifications',
    'storages',

    # project apps
    'accounts',
    'tweets',
    'friendships',
    'newsfeeds',
    'comments',
    'likes',  # 完整的用户行为闭环[读:看到Tweet + 写:点赞]，企业用来做监控[如果点赞数量突然大幅下降，可能是系统链路出问题了]
    'inbox',  # [不能叫 notifications，防止冲突] [单数: 每个用户只有一个inbox]
]

REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,    # Page: count, next, previous, results
    # client 客户端传入这个参数
    # web client        page_size = 20 to 50
    # phone app client  page_seize = 10
    # pad app client,
    # 嵌入式 client ...

    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
    ],
}

# 所有的 HTTP 请求和响应都会按顺序依次经过这些 middleware
# Client Request → [Middleware1] → [Middleware2] → ... → View
# Client Response ← [Middleware1] ← [Middleware2] ← ...    ↓
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    "debug_toolbar.middleware.DebugToolbarMiddleware",
]

ROOT_URLCONF = 'twitter.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'twitter.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'twitter',
        'HOST': '0.0.0.0',
        'PORT': '3306',
        'USER': 'root',
        'PASSWORD': 'zhuzhu',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# AUTH_USER_MODEL = 'django.contrib.auth.models.User'   django User 模型
# AUTH_USER_MODEL = 'users.models.User'                 自定义  User 模型

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/
STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


"""
MEDIA_URL = '/media/'
❌ 会把 服务器 变成 stateful

结构化数据 Structured Data
文件型数据 File Based Data / Unstructured Data [图片 音频 文件]
"""
# 设置存储用户上传文件的 storage 用什么系统
DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
TESTING = ((" ".join(sys.argv)).find('manage.py test') != -1)
if TESTING: # 单元测试 在本地离线运行: 效率高 + 没有 web 依赖
    DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'

# 当用 s3boto3 作为用户上传文件存储时，需要按照你在 AWS 上创建的配置来设置你的 BUCKET_NAME
# 和 REGION_NAME, 这个值你可以改成你自己创建的 bucket 的名字和所在的 region
AWS_STORAGE_BUCKET_NAME = 'django-twitter-zhuzhu'
AWS_S3_REGION_NAME = 'us-west-1'

# 你还需要在 local_settings.py 中设置你的 AWS_ACCESS_KEY_ID 和 AWS_SECRET_ACCESS_KEY
# 因为这是比较机密的信息，是不适合放在 settings.py 这种共享的配置文件中共享给所有开发者的
# 真实的开发场景下，可以使用 local_settings.py 的方式，或者设置在环境变量里的方式
# 这样这些机密信息就可以只被负责运维的核心开发人员掌控，而非所有开发者，降低泄露风险
# AWS_ACCESS_KEY_ID = 'YOUR_ACCESS_KEY_ID'          类似 账户
# AWS_SECRET_ACCESS_KEY = 'YOUR_SECRET_ACCESS_KEY'  类似 密码

# media 的作用适用于存放被用户上传的文件信息
# 当我们使用默认 FileSystemStorage 作为 DEFAULT_FILE_STORAGE 的时候
# 文件会被默认上传到 MEDIA_ROOT 指定的目录下
# media 和 static 的区别是：
# - static 里通常是 css,js 文件之类的静态代码文件，是用户可以直接访问的代码文件
# - media 里使用户上传的数据文件，而不是代码
MEDIA_ROOT = 'media/'   # if TESTING: ... [.gitignore]

# https://docs.djangoproject.com/en/3.1/topics/cache/
# memcached 安装方法: apt-get install memcached
# 然后安装 python 的 memcached 客户端：use `pip install python-memcached`
# DO NOT `pip install memcache or django-memcached`
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.memcached.PyMemcacheCache',
        'LOCATION': '127.0.0.1:11211',
        'TIMEOUT': 86400,   # ttl: time to live 保证数据的一致性
        # 1. 超时
        # 2. 主动删除
        # 3. 内存不够用，访问频率低的被删除 [LRU: 缓存100条]

        # from django.core.cache import cache
        # cache.get('key1')
        # cache.set('key1', 'val1', timeout=100)
        # cache.get('key1') -> return val1
        # ... 100 seconds later
        # cache.get('key1') -> 不存在，返回 None
    },
    'testing': {
        'BACKEND': 'django.core.cache.backends.memcached.PyMemcacheCache',
        'LOCATION': '127.0.0.1:11211',  # 本机 | memcached服务器的ip地址 [AWS: XXX.XXX.com]
        'TIMEOUT': 86400,
        'KEY_PREFIX': 'testing',
        # 实际存储的 key: 'testing_followings:3'
        
        # Django 在每个测试结束后 只会删除测试数据库
        # 不会自动清空缓存，因为 cache 是外部系统（memcached, redis）
        # 所以测试期间写入的 cache key 仍然存在，需要手动清理
        # def setUp(self):
        #   self.clear_cache()
    },
}

# Redis
# 安装方法: sudo apt-get install redis
# 然后安装 redis 的 python 客户端: pip install redis
REDIS_HOST = '127.0.0.1'
REDIS_PORT = 6379
REDIS_DB = 0 if TESTING else 1  # Redis 的数据库: 0, 1, 2, 3, ...
REDIS_KEY_EXPIRE_TIME = 7 * 86400    # in seconds


try:
    from twitter.local_settings import *
except:
    pass